### ISSUE TITLE
 Improved documentation for very typical topics missing or hard to find

### ISSUE THREAD

**Issue by Gaibhne** [pieces-app/documentation#10]
I just spent about ten minutes, which is more than I would typically spend on a (to me) unknown new project, and which I suspect most people will not spend, trying to find out:

- Can this be used without having my code/data in snippets leave my local PC/local network ? I, like many people, work in a professional software company, and we have many complicated rules governing any exposure of our internal product, source codes, customer data, names, etc. which I would absolutely not want to hop through in order to test a project, and possibly not ever. If 'offline/private' mode is not supported, which for a project like this I could understand being a technical limitation, then that needs to be stated upfront in the FAQ, so I can decide to either move on or to invest the time needed to get that cleared with management. I searched for "offline", "self hosted", "private mode" and similar terms to no avail.

- I could not find anything on pricing. I don't know whether this information is hidden intentionally, but hiding the cost of something instantly sends up warning bells for me. It means either your pricing is in some way so bad that you want to tempt me before even telling me the price, or that my own data or usage patterns or similar are sold to make the profit a company needs to not close their offices.

Both of these informations being hard to find have made me instantly suspicious and typically, I would simply move on from a project as I would consider it probably being something shady. A friend recommending this project means you have my benefit of the doubt, but imagine how many people like me spend a minute or two searching for those things and then move on, mentally filing Pieces under "probably some ripoff/data seller" ?

In the projects own interest, I would very much recommend featuring answers to those two topics much, MUCH more prominently, assuming answers are available at all at the moment.

**Comment by jordan-pieces** [comment]
@Gaibhne thank you so much for bringing this up! Currently I am working on a new page that dives into the security aspects of Pieces and will explain the ins and outs of offline use vs online usage. Pieces is built with users specifically like you in mind in order to meet any data restrictions in organizations that you work at or for. 

Once that page is completed i will add a link to it here for your viewing and for others benefit over time. 

In regards to pricing, Pieces is currently free and does not cost a thing - there may be some opportunity to pay for faster features in the future as well. :)

**Comment by jordan-pieces** [comment]
@Gaibhne here is the new page ! https://docs.pieces.app/product-highlights-and-benefits/privacy-security-data

Let us know if there are any further questions - have a wonderful weekend!
