### ISSUE TITLE
Why does Pieces require Admin rights for updates?

### ISSUE THREAD

**Issue by codingbutstillalive** [pieces-app/documentation#107]

**Comment by jordan-pieces** [comment]
This is due to the PKG installer needing to write as root to your application directory. The only way to modify the application after it is written as root by the PKG installer, it needs those permissions again.

To avoid this, you can use the DMG installer that is available here: 

[macOS installation](https://docs.pieces.app/installation-getting-started/macos)

**Be sure to completely uninstall both Pieces OS and Pieces Desktop first before installing the DMG versions**
- note: you will keep your snippets and all your data 

To get there: 

1. Navigate to the link: [macOS installation](https://docs.pieces.app/installation-getting-started/macos)
2. Click the accordion dropdown on the page below the two black install buttons at the top 
3. Download both OS Server + Pieces Desktop DMG versions of the applications 

A Screenshot for reference: 

![Screenshot 2023-08-01 at 11 26 48 AM](https://github.com/pieces-app/documentation/assets/55861512/ea83c16a-fe3d-4826-837b-c9d3c5aeb842)

**Comment by jordan-pieces** [comment]
Let us know how this goes @codingbutstillalive and this should remove this issue for you going forward and installing updates! :)

**Comment by codingbutstillalive** [comment]
Thank you. Any notes on how to succeed with a complete deinstallation?

**Comment by jordan-pieces** [comment]
Just make sure that you remove both applications from your "/applications" folder and then remove them from your Trash and that should do it. be sure to keep any folders that are in other locations so your snippets are not disturbed

**Comment by codingbutstillalive** [comment]
Thank you very much!

jwaf ***@***.***> schrieb am Di. 1. Aug. 2023 um 19:20:
