### ISSUE TITLE
Windows Tab is showing for Mac in installation page 

### ISSUE THREAD

**Issue by chottuthejimmy** [pieces-app/documentation#117]
At : [what am I installing](https://docs.pieces.app/installation-getting-started/what-am-i-installing). 

The default tab is showing as windows in mac.

https://github.com/pieces-app/documentation/blob/d1389c305ea0b75f07be3acca1b99e99fd3657a0/docs/installation-getting-started/what-am-i-installing.mdx#L68

https://github.com/pieces-app/documentation/assets/108192034/ee4cb1e3-82b7-480b-9378-8437d4babfc1

**Comment by jordan-pieces** [comment]
The default is set to windows and it does not "detect" the OS that is installed here. JS doesn't perform well but we can create a PR to test more of this. If you want to start on testing this problem feel free to branch and then create a PR linked to this issue that I can take a look at - otherwise we can come back to this in the near future @chottuthejimmy

**Comment by chottuthejimmy** [comment]
I sure did some testing on wes's some random branch , but couldn't really figure out what was working. https://github.com/pieces-app/documentation/pull/118 . I think it ended up working in Mac but not on windows for some reason. [Link](https://docs.pieces.app/~118/installation-getting-started/what-am-i-installing) . But really appreciate for trusting me with this and will get into it rn 🫡 😊 .

**Comment by jordan-pieces** [comment]
absolutely just keep me updated on your progress and ping me as you are finishing up later and I can take a peek at your PR :)

**Comment by chottuthejimmy** [comment]
Lol u can't really view the bot if the pr is marked as closed ig , so I have just kept it open , we can experiment over there and once its sorted will create an actual pr .

**Comment by jordan-pieces** [comment]
I have a decent inkling that this isnt going to work since in the past it has been very difficult to add custom solutions for things like this. but we can continue to look in the future. Ill close this issue for now and we can reopen it all next week or in the next few weeks to see how we can improve this and potentially pair program together to get it setup
