### ISSUE TITLE
Huge memory consumption by Pieces OS

### ISSUE THREAD

**Issue by Mr-Atanu-Roy** [pieces-app/documentation#164]
I am current using pieces for windows on windows 11. And on my system its consuming **huge memory**. 

![Screenshot (1)](https://github.com/pieces-app/documentation/assets/100309120/10f5cb72-8ba1-445c-b13f-b547627a26a4)

Here as it can be observed that huge memory is consumed by Pieces OS and also its enabled on startup. 
So I request to look after this matter.

**Comment by jordan-pieces** [comment]
Hey @Mr-Atanu-Roy - hope you are well and thanks for reaching out about this issue! We have had a few others users bring this up recently and are looking into reducing this currently. Since Pieces OS runs on your device locally for security and also now has the included ML model selection to run those models on your device as well. 

We are working on offloading these models and making sure that when Pieces OS is running in the background and sitting idle, it will take up less of your memory on your computer. :) 

This should be coming out in a release in this Quarter - I will make a note to try and reach back out to you when this is done! Im going to tag @brian-pieces to provide any other information if he would like to share or if you would like more info on this.

**Comment by Mr-Atanu-Roy** [comment]
Awesome, thanks for the update!

**Comment by Mr-Atanu-Roy** [comment]
Oh nice,,
I downloaded and tested it and now I have seen a rapid decrease in memory
consumption after this update.

**Comment by jordan-pieces** [comment]
@Mr-Atanu-Roy awesome that is so great to hear! We are hoping that you continue to enjoy experiences with Pieces for Developers and are always here to lend a hand. And if there are other issues that come up like this one, please feel free to reach out and create another issue on this repo here, and we will get back to you as soon as possible. 

Also if you have not already and would like to stay in touch, join our [discord](https://discord.gg/getpieces) community as we always love constructive feedback and creating improved experiences for our users where they discover them. Hope you have a wonderful day! 

I will close this issue soon to mark it as completed on our side. :)

**Comment by Mr-Atanu-Roy** [comment]
One more thing I would like to know is: what does this feature actually do in the background?
And I think for now users always have to manually click the **Optimize memory usage** button. But it would be better if it is saved as a personal setting in the preference tab of Pieces Suite or OS.

**Comment by jordan-pieces** [comment]
I am going to be closing this issues as it seems resolved - hope you are well @Mr-Atanu-Roy and let us know if there is anything else in the future. feel free to reach out in discord or open another issue here !
