### ISSUE TITLE
Not able to install pieces os on Mac

### ISSUE THREAD

**Issue by dreambit** [pieces-app/documentation#240]
Both pkg, dmg, brew not working

<img width="264" alt="image" src="https://github.com/pieces-app/documentation/assets/1479661/678b64cb-a25b-4d77-9a07-02e1f566c720">
<img width="265" alt="image" src="https://github.com/pieces-app/documentation/assets/1479661/9cfe6ad6-b641-4341-bf04-738a25ed80b6">

brew 

<img width="431" alt="image" src="https://github.com/pieces-app/documentation/assets/1479661/dc96facd-9f43-47d0-a4dc-01e0dfebc62a">

**Comment by jordan-pieces** [comment]
hey @dreambit thank you for reaching out - we will need some more information about your device to see how we can be of assistance here. I've attached @rosie-at-pieces to this issue for her awareness, but want to get this issue sent over to our support tickets/issues so it can be addressed 👍  

When you open that issue can you share details on your operating system, and other details found in the **Bug Support** issue template, that way we can better assist you. 

once that issue is open we can link it here and be sure that you are assisted. let me know if you have any questions and we can go from there! 

[Click here to create your support issue](https://github.com/pieces-app/support/issues)

**Comment by Boxroma** [comment]
I am also Experiencing the same issue. Is there a working solution or should I also create a support issue?

**Comment by jordan-pieces** [comment]
@dreambit @Boxroma just want to check in here - closing this issue and just wanted to check in and see if any additional assistance is needed here. If there are still issues please reopen this issue and share any problems, or follow up on the corresponding issue on the support repo 👍

**Comment by Boxroma** [comment]
@jordan-pieces. This issue is closed for me. Turns out my unstable internet was not downloading the full file and without a checksum, I was never able to tell how big the file was supposed to be. After using a third-party to download the setup file it was all good after that. Thanks.
