### ISSUE TITLE
bug: not installing on kali linux 

### ISSUE THREAD

**Issue by priyankarpal** [pieces-app/documentation#267]
not installing on Kali Linux (Xfce) 

- `sudo snap install pieces-os`
after the error log 

```
error: cannot communicate with server: Post "http://localhost/v2/snaps/pieces-os": dial unix /run/snapd.socket: connect: no such file or directory

```

**Comment by jordan-pieces** [comment]
hey @priyankarpal - we currently offer limited support for different linux distros, and due to the number of flavors in each of these distributions they all can work in slightly different ways. 

If you wouldnt mind creating an issue on our [support repo](https://github.com/pieces-app/support) that way we can track this issue and other kali linux users can be made aware of any issues they may encounter. 

When you create that issue, please try and add as much additional information as possible so we may help assist you such as any screenshots or further information - is always appreciated 👍

**Comment by priyankarpal** [comment]
sure

**Comment by jordan-pieces** [comment]
going to link this issue to the opened support ticket and then mark this as closed here on the documentation repo 😄 

Linked Support Discussion: https://github.com/pieces-app/support/discussions/14#discussioncomment-8563986

cc: @priyankarpal & @rosie-at-pieces
