### ISSUE TITLE
Updates to Current EAP/WPE Pages

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#397]

**Comment by rosie-at-pieces** [comment]
Add at the top of the Workstream Context [page](https://docs.pieces.app/product-highlights-and-benefits/workstream-context):
"This feature is currently only available to users enrolled in the Early Access Program. If you would like to be a part of this program, please take a look at our [Early Access Program documentation.](https://docs.pieces.app/early-access-program)"

**Comment by mason-at-pieces** [comment]
@rosie-at-pieces See changes here: https://documentation-git-wpe-eap-updates-pieces-for-developers.vercel.app/product-highlights-and-benefits/live-context

I said that this is still in `Alpha` as well.

**Comment by rosie-at-pieces** [comment]
@mason-at-pieces we gotta make a bunch of changes to this anyways today with the new enabling/disabling

**Comment by mack-at-pieces** [comment]
Updates for Live Context powered by the WPE:
- Live Context is now in alpha
- Users have general access to use Live Context within their Copilot Chats
- Only available to macOS & Windows users with Linux support coming ASAP 🙏🏼 
- Users do not have to be authenticated to use Live Context
- They turn on Live Context by clicking the button in the "Set Context" region of the new chat, or via the "Context" button to the left of the Copilot Input
- Live Context is powered by the Workstream Pattern Engine (WPE), so the WPE must be on in order to use the feature
- Maybe add a callout that recommends the user click around their workflow between chats, websites, emails, code, etc while the WPE is running before asking a question to get the most value out of it (i.e. data capture)
- Users can manage the WPE via the main app settings view
- They can activate/deactivate the WPE, as well as pause it for pre-set durations
- Users can also clear all data associated with the WPE, for pre-set durations or all-time

Updates for EAP:
- Mainly a "reduction / comment out" motion here to remove the content specific to the WPE test
- Make sure we have info on how to "Join EAP" and how to "Leave EAP"
- Mostly specific to doing this via the "Account" section of the main settings view in the Desktop App

**Comment by rosie-at-pieces** [comment]
generic EAP page:

https://docs.google.com/document/d/1F5daDBi7MiBxkliRGpHZc0TinzuBqeb2TixyoUiaFIQ/edit?usp=sharing

**Comment by rosie-at-pieces** [comment]
![Turn Off:Pause WPE Big](https://github.com/pieces-app/documentation/assets/152189388/6002b89b-018b-4722-80eb-46c9f43ee203)
