### ISSUE TITLE
Obsidian Plugin - Documentation Breakout 

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#83]
We need to move the Obsidian docs from a single page to a multi page layout to support more features being added and more in depth conversation around each of the features. Lets get all the features updated first and then we can figure out the layout or organization of them all.

These are what is currently listed on the docs site on the one page for the plugin. But think about sections like: 
- Using the Plugin 
- Managing plugin settings 
- Faqs
- things like this ^^

Currently Documented Obsidian Features: 

- Installation and getting started instructions 
- Save your snippets 
- find your snippets 
- use your snippets 
- share your snippets 
- embedded buttons 
- data, privacy, security, and offline first approach 
- Having trouble?
- Help and support

**Comment by caleb-at-pieces** [comment]
New Features:

qGPT:

- Make sure POS is open, and updated to at least 5.1.2
- To view the Copilot, open the pieces plugin and click the bot logo on the top slider to switch to Copilot
- The copilot will load in your entire vault as context for the chatbot. This means you can query your Obsidian vault completely with plain text and we will semantically match your question to the relevant notes you have.
- Simply begin asking questions in the input text prompt regarding your notebooks and watch the magic!
- Each time you enter a query you will also receive suggested queries relating to your conversation, simply click one of the suggested queries buttons in order to continue the conversation with that query.
- Each response from the Copilot will also contain the relevant notebooks that it was able to gain context from in order to answer your question, click on one of those buttons in order to open that notebook in your editor.

enrich embedded button:
- with this release we also added a new button to the embedded code block buttons titled 'Enrich Code block'. 
- Upon clicking this button, we will generate a title and description for that code block and automatically add it into the markdown surrounding the code block.

realtime streaming:

We added a websocket connection with this release as well. This means that all of the changes you would make across any Pieces integration (i.e PFD, VSCode, Jetbrains, etc) should automatically be reflected in the plugin.

**Comment by wes-at-pieces** [comment]
I get get to work writing out the docs for these new features. Then, we can collaborate to integrate that new content into whatever new structure we come up with. Working on this now!
