### ISSUE TITLE
Jupyter Plugin - Documentation Breakout 

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#84]
We need to move the Jupyter docs from a single page to a multi page layout to support more features being added and more in depth conversation around each of the features. Lets get all the features updated first and then we can figure out the layout or organization of them all.

These are what is currently listed on the docs site on the one page for the plugin. But think about sections like:

- Using the Plugin
- Managing plugin settings
- Faqs
- things like this ^^

Currently Documented Jupyter Features:
- steps to install 
- find your snippetes 
- use your snippets 
- share your snippets 
- embedded buttons 
- data privacy and security 
- having trouble?
- can i customize?
- help and support

**Comment by caleb-at-pieces** [comment]
New Features:

qGPT:
- Make sure POS is open, and updated to at least 5.1.2
- To view the Copilot, open the pieces plugin and click the bot logo on the top slider to switch to Copilot
- The copilot will traverse the directory you launched jupyterlab from in order to load in your notebooks as context for the chatbot, this means if you have multiple notebooks in that same directory, it will load in all of them for you to query.
- Simply begin asking questions in the input text prompt regarding your notebooks and watch the magic!
- Each time you enter a query you will also receive suggested queries relating to your conversation, simply click one of the suggested queries buttons in order to continue the conversation with that query.
- Each response from the Copilot will also contain the relevant notebooks that it was able to gain context from in order to answer your question, click on one of those buttons in order to open that notebook in your editor.

enrich selection:
- With the new release, you can also select any text within a code cell in your notebook, right click, and add a useful description to it.

realtime streaming:
- We added a websocket connection with this release as well. This means that all of the changes you would make across any Pieces integration (i.e PFD, VSCode, Jetbrains, etc) should automatically be reflected in the plugin.

**Comment by jordan-pieces** [comment]
@caleb-at-pieces just want to double check that these are pretty complete - i can get these on a PR for Jupyter. we can start with updating the sections and getting the most up to date features on the docs for now.

**Comment by caleb-at-pieces** [comment]
> @caleb-at-pieces just want to double check that these are pretty complete - i can get these on a PR for Jupyter. we can start with updating the sections and getting the most up to date features on the docs for now.

Yes, this is up to date.
