### ISSUE TITLE
Windows Suite Installation Not Completing

### ISSUE THREAD

**Issue by OryxConceptual** [pieces-app/documentation#90]
Downloading the Windows Suite Installer does not actually finish after reaching 100%. 15 minutes have passed with both the Pieces OS and Pieces for Dev. sitting at 100%.
![image](https://github.com/pieces-app/documentation/assets/103851148/d01b8fcb-5936-4fe6-b153-49fc6cbb4082)
After closing the installer it seems to be working just fine. Just no actual confirmation was shown that it had completed.

**Comment by jordan-pieces** [comment]
@OryxCodeBox this is a very interesting outcome, but happy that everything appears to be working alright. Just to confirm i wanted to make sure that Pieces for Developers and Pieces OS are running alright? If not let us know and we can work with you to get it fixed and running.

Have you noticed anything further in regards to strange functionality since seeing this? @nathan-courtney-pieces is currently out of office, but can work with him to investigate this when he is back. I will keep you updated if we can recreate it. 

After you quit the Pieces Suite Installer and relaunch it, does the launcher itself still say that its at 100% and installing?

Let us know and we will talk to you more soon!

**Comment by jordan-pieces** [comment]
hey @OryxConceptual I am going to close this issue as we have not heard back from you and believe this issue to be resolved in an updated version of the Pieces Suite Installer.

If you have any other questions or are still experiencing this issue, please feel free to open up another issue.
